### ISSUE TITLE
Unable to use installer on linux

### ISSUE THREAD

**Issue by Krohmium** [jolie/jolie#144]
I'm on Kubuntu 18.04 and tried it with current OpenJDK and Oracle Java 10.
I tried installing jolie by installer on Linux and it always abort with interupt exceptions:

```
sudo java -jar jolie-1.6.4.jar
Aug. 16, 2018 2:17:42 NACHM. jolie.Interpreter logSevere
SCHWERWIEGEND: [installer.ol] java.lang.InterruptedException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax/activation/FileTypeMap
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at jolie.ExecutionThread.join(ExecutionThread.java:481)
        at jolie.Interpreter.runCode(Interpreter.java:1088)
        at jolie.Interpreter.run(Interpreter.java:1132)
        at jolie.Jolie.main(Jolie.java:60)
Caused by: java.lang.NoClassDefFoundError: javax/activation/FileTypeMap
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
        at java.base/java.lang.Class.getConstructor0(Class.java:3295)
        at java.base/java.lang.Class.newInstance(Class.java:532)
        at jolie.runtime.embedding.JavaServiceLoader.load(JavaServiceLoader.java:50)
        at jolie.process.InitDefinitionProcess.run(InitDefinitionProcess.java:59)
        at jolie.SessionThread.runProcess(SessionThread.java:468)
        at jolie.ExecutionThread.run(ExecutionThread.java:469)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.activation.FileTypeMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at jolie.JolieClassLoader.loadClass(JolieClassLoader.java:120)
        ... 13 more

        at jolie.ExecutionThread.join(ExecutionThread.java:485)
        at jolie.Interpreter.runCode(Interpreter.java:1088)
        at jolie.Interpreter.run(Interpreter.java:1132)
        at jolie.Jolie.main(Jolie.java:60)

```
When trying to install version 1.5 I get a slightly different error:

```
sudo java -jar jolie-1.5.0.jar 
jolie.InterpreterException: jolie.lang.parse.ParserException: /home/nibenon/Downloads/file:/tmp/jolie_installer_tmp10403379467124845077/dist/jolie/include/types/IOException.iol:23: error: File not found: JavaException.iol. Found token type STRING, token content JavaException.iol
        at jolie.Interpreter.buildOOIT(Interpreter.java:1270)
        at jolie.Interpreter.init(Interpreter.java:1037)
        at jolie.Interpreter.run(Interpreter.java:1112)
        at jolie.Jolie.main(Jolie.java:59)
Caused by: jolie.lang.parse.ParserException: /home/nibenon/Downloads/file:/tmp/jolie_installer_tmp10403379467124845077/dist/jolie/include/types/IOException.iol:23: error: File not found: JavaException.iol. Found token type STRING, token content JavaException.iol
        at jolie.lang.parse.AbstractParser.throwException(AbstractParser.java:197)
        at jolie.lang.parse.OLParser.parseInclude(OLParser.java:714)
        at jolie.lang.parse.OLParser._parse(OLParser.java:202)
        at jolie.lang.parse.OLParser.parseInclude(OLParser.java:728)
        at jolie.lang.parse.OLParser._parse(OLParser.java:202)
        at jolie.lang.parse.OLParser.parseInclude(OLParser.java:728)
        at jolie.lang.parse.OLParser._parse(OLParser.java:202)
        at jolie.lang.parse.OLParser.parse(OLParser.java:183)
        at jolie.Interpreter.buildOOIT(Interpreter.java:1218)
        ... 3 more
```

and then it hangs.

In Version 1.5 it seems like the installer is looking in the wrong path.

Install with ant works perfectly fine

**Comment by fmontesi** [comment]
Thanks for the report. We don't support Java 9 or above yet, due to the new module system that doesn't include some libraries we use that were previously included by default. The recommended solution is to include these libraries in the project, we're working on that. Will repost here when done.

**Comment by fmontesi** [comment]
Should work now in Jolie 1.7.0. Let us know if the issue appears again! :-)
