### ISSUE TITLE
HTTP GWT-RPC

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#21]
During writing a unit test for GWT-RPC I got this exception:

Exception in thread "Thread-46" com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException: This application is out of date, please click the refresh button on your browser. ( Malformed or old RPC message received - expecting version between 5 and 7 )
        at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.prepareToRead(ServerSerializationStreamReader.java:418)
        at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:237)
        at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:167)
        at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:124)
        at jolie.net.HttpProtocol.parseGWTRPC(HttpProtocol.java:893)
        at jolie.net.HttpProtocol.recv_parseMessage(HttpProtocol.java:1105)
        at jolie.net.HttpProtocol.recv_internal(HttpProtocol.java:1243)
        at jolie.net.http.HttpUtils.recv(HttpUtils.java:129)
        at jolie.net.HttpProtocol.recv(HttpProtocol.java:1334)
        at jolie.net.SocketCommChannel.recvImpl(SocketCommChannel.java:95)
        at jolie.net.CommChannel.recv(CommChannel.java:194)
        at jolie.net.CommCore$CommChannelHandlerRunnable.run(CommCore.java:601)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fmontesi** [comment]
It looks like the client and server version are not aligned?

**Comment by mwallnoefer** [comment]
Let us continue the discussion in #23.

**Comment by the-lost-explorer** [comment]
Did you manage to address this error? #23 doesn't seem to answer! Please help, I have the exact same issue during load testing of my gwt application. The ubiq load test plugin doesn't seem to convert xml back to gwtrpc.

**Comment by fmontesi** [comment]
@the-lost-explorer Can you share a stack trace?
