### ISSUE TITLE
joliedoc - error throw during the generation of docs, in files using the new syntax for modules.

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/jolie#308]
Trying to generate the documentation for this simple process

``
from File import File
service newSyntax {
    embed File as File

    main {
        nullProcess
    }
}
``

the joliedoc throw the following error:

``

May 10, 2021 9:51:24 AM joliedoc.ol
INFO: [joliedoc.ol] Thrown unhandled fault: NullPointerException
Content (if any)
        .stackTrace[0] = java.lang.NullPointerException
        at joliex.meta.MetaJolie.getTypeDefinition(MetaJolie.java:276)
        at joliex.meta.MetaJolie.insertTypeDefinition(MetaJolie.java:268)
        at joliex.meta.MetaJolie.getFault(MetaJolie.java:604)
        at joliex.meta.MetaJolie.getInterface(MetaJolie.java:439)
        at joliex.meta.MetaJolie.getInterfaceAndInsertTypes(MetaJolie.java:620)
        at joliex.meta.MetaJolie.getOutputPort(MetaJolie.java:485)
        at joliex.meta.MetaJolie.getOutputPortMetaData(MetaJolie.java:911)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at jolie.runtime.JavaService.requestResponseCallable(JavaService.java:260)
        at jolie.runtime.JavaService.callOperation(JavaService.java:389)
        at jolie.runtime.embedding.JavaCommChannel.lambda$sendImpl$0(JavaCommChannel.java:86)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
 : string
``

The old syntax currently work very well without problems.

**Comment by fmontesi** [comment]
The file is incorrect, it should be `from file import File` (notice the lowercase). I still get the error though, just reporting it here for the others.

**Comment by fmontesi** [comment]
Fixed.
