### ISSUE TITLE
Bug in extracting http parameters under osc root

### ISSUE THREAD

**Issue by klag** [jolie/jolie#430]
I added a test in this branch for reproducing the bug

https://github.com/jolie/jolie/tree/fix/http-protoco-parameter-recognition

**Comment by fmontesi** [comment]
@klag: Could you write here the error that you get from the test?

@bmaschio: Could you look into this? I think it's your latest HTTP patch.

**Comment by klag** [comment]
`╰─── stackTrace:string = "jolie.net.http.UnsupportedMethodException: 
	at jolie.net.http.Method.fromString(Method.java:56)
	at jolie.net.HttpProtocol.send_getRequestMethod(HttpProtocol.java:857)
	at jolie.net.HttpProtocol.send_internal(HttpProtocol.java:1011)
	at jolie.net.http.HttpUtils.send(HttpUtils.java:145)
	at jolie.net.HttpProtocol.send(HttpProtocol.java:1084)
	at jolie.net.SocketCommChannel.sendImpl(SocketCommChannel.java:118)
	at jolie.net.SelectableStreamingCommChannel._send(SelectableStreamingCommChannel.java:86)
	at jolie.net.SelectableStreamingCommChannel.lambda$send$0(SelectableStreamingCommChannel.java:75)
	at jolie.util.Helpers.lockAndThen(Helpers.java:123)
	at jolie.net.SelectableStreamingCommChannel.send(SelectableStreamingCommChannel.java:75)
	at jolie.process.RequestResponseProcess.runBehaviour(RequestResponseProcess.java:245)
	at jolie.process.RequestResponseProcess$1.run(RequestResponseProcess.java:117)
	at jolie.process.RequestResponseProcess.run(RequestResponseProcess.java:142)
	at jolie.process.DefinitionProcess.run(DefinitionProcess.java:42)
	at jolie.SessionThread.runProcess(SessionThread.java:410)
	at jolie.ExecutionThread.run(ExecutionThread.java:479)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

The error should be generated at row 1439 of HTTPProtocol

`String opConfigMethod = opConfig.getFirstChild( Parameters.METHOD ).strValue();`

This row adds node `method` under osc.opname tree even if it does not exist. Such a node, the, raises an error ato row 857 of HttpProtocol

**Comment by klag** [comment]
I locally trued to replace row 1439 with the following code and it seems to work.

```
String opConfigMethod = "";
if( opConfig.hasChildren( Parameters.METHOD ) ) {
opConfigMethod = opConfig.getFirstChild( Parameters.METHOD ).strValue();
}
```
@bmaschio @fmontesi If you think it is sufficient, I can push this fix in the opened branch so it is possible to merge

**Comment by klag** [comment]
ping!

**Comment by fmontesi** [comment]
Good catch. I made a one-liner fix in `master`:

```
String opConfigMethod = opConfig.firstChildOrDefault( Parameters.METHOD, Value::strValue, "" );
```

which is a way of doing that `if` declaratively.

Your test passes in master now, but I'm wondering whether @bmaschio intended to have that whenever a person uses a template, the method must also be specified?.. We'd need to check for that separately and throw an error in that case. @bmaschio, I'm leaving this note for you later. :)
