### ISSUE TITLE
HTTP templates which contain _ underscores

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#511]
When we generate interfaces with `openapi2jolie` we get the URI router components prefixed with `_` (e.g. `_pcode`). Unfortunately, such names are illegal in our HTTP template parser:
```
    inputPort Web {
        location: "socket://localhost:9000"
        protocol: http {
            .osc.getArticle.template = "/api/article/{_pcode}"
            .osc.getArticle.method="get";
            .osc.getArticle.statusCodes.Fault404 = 404
```
So we get the following stacktrace:
```
Exception in thread "Thread-1" java.util.regex.PatternSyntaxException: capturing group name does not start with a Latin letter near index 3 (?<_pcode>[^\/]+)
   ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.groupname(Pattern.java:2947)
...
        at com.damnhandy.uri.template.Expression.buildMatchingPattern(Expression.java:363)
        at com.damnhandy.uri.template.Expression.getMatchPattern(Expression.java:377)
...
        at jolie.uri.UriUtils.match(UriUtils.java:39)
        at jolie.net.HttpProtocol.recv_templatedOperation(HttpProtocol.java:1224)
        at jolie.net.HttpProtocol.recv_internal(HttpProtocol.java:1386)
        at jolie.net.http.HttpUtils.recv(HttpUtils.java:324)
        at jolie.net.HttpProtocol.recv(HttpProtocol.java:1527)
...
```
@fmontesi + @klag any idea how to mitigate this? Of course I can rename the parameters in the generated interface file, but this does not seem a clean approach to me. Generated code should work out of the box.

**Comment by fmontesi** [comment]
Can you show the source openapi spec for that op?

@klag is there a particular reason for the _ prefix or can it just be removed?

**Comment by mwallnoefer** [comment]
```
     "/artikel/{code}": {
       "get": {
         "operationId": "getArtikel",
         "produces": [ "application/json" ],
         "parameters": [{
           "name": "code",
           "in": "path",
           "required": true,
           "type": "string",
           "pattern": "^IT\\d{6}$|^DE\\d{8}$"
         }],
         "responses": {
           ...
         }
       },
```

**Comment by fmontesi** [comment]
The issue is that we're using a 3rd party lib for parsing URI templates IIRC. We could ofc make a PR there, as well.

But I don't think what we're doing now looks idiomatic anyway. Shouldn't we just use the same name that the user put, and then add a prefix (like q) or suffix (to avoid the _ problem) to query parameters? If there's still a conflict, we should output an error or keep suffixing maybe?...

**Comment by mwallnoefer** [comment]
I had another look into this and I guess that it is not so easy to fix, since the underscore works pretty much like a qualifier. Just have a look at the following snippet (but @klag could explain it better):
https://github.com/jolie/jolie/blob/a1be018372021d2bcd3a374d1b89567e9ba80f17/include/services/openapi/openapi2jolie.ol#L60-L64

And also here: https://github.com/jolie/jolie/blob/a1be018372021d2bcd3a374d1b89567e9ba80f17/include/services/openapi/openapi2jolie.ol#L325-L331

**Comment by mwallnoefer** [comment]
@klag what do you think?
