### ISSUE TITLE
Missing mutex in jolie.net.CommCore

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#69]
Exception in thread "testClient.ol-testClient.ol-SelectorThread" java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at jolie.net.CommCore$SelectorThread.run(CommCore.java:865)

**Comment by fmontesi** [comment]
Is that on master or java8?

**Comment by mwallnoefer** [comment]
this is "master"

**Comment by fmontesi** [comment]
Right, register and unregister may cause a race while the interpreter shuts down. Can you try now?

**Comment by mwallnoefer** [comment]
Yes, this fixes it but now I get:
<code>
Exception in thread "Thread-137" java.lang.NullPointerException
        at jolie.runtime.TimeoutHandler$Comparator.compare(TimeoutHandler.java:67)
        at jolie.runtime.TimeoutHandler$Comparator.compare(TimeoutHandler.java:62)
        at java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:699)
        at java.util.PriorityQueue.siftDown(PriorityQueue.java:667)
        at java.util.PriorityQueue.poll(PriorityQueue.java:578)
        at java.util.AbstractQueue.remove(AbstractQueue.java:113)
        at jolie.Interpreter.checkForExpiredTimeoutHandlers(Interpreter.java:401)
        at jolie.Interpreter.addTimeoutHandler(Interpreter.java:379)
        at jolie.net.AbstractCommChannel$ResponseReceiver.sleep(AbstractCommChannel.java:140)
        at jolie.net.AbstractCommChannel$ResponseReceiver.run(AbstractCommChannel.java:236)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
</code>

**Comment by mwallnoefer** [comment]
I tested another example and the mentioned issue remains: `synchronized( this )` seems not to be enough or wrong (maybe `synchronized( selectingMutex )`?).

**Comment by mwallnoefer** [comment]
@fmontesi Any news on this?

**Comment by fmontesi** [comment]
Should be fixed now. (Last famous words.. :-) )

**Comment by mwallnoefer** [comment]
Seems to be gone.
